basePath: /
definitions:
  request.ProductForm:
    properties:
      cost:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server
  termsOfService: http://swagger.io/terms/
  title: 4.Mongo Web Project
  version: "2.0"
paths:
  /products:
    get:
      description: Returns the list of the products
      produces:
      - application/json
      responses: {}
      summary: Get all products
      tags:
      - products
    post:
      description: Returns the product
      parameters:
      - description: shop product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/request.ProductForm'
      produces:
      - application/json
      responses: {}
      summary: Save product
      tags:
      - product
  /products/{id}:
    get:
      description: Returns the product by id
      parameters:
      - description: Product id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get product by id
      tags:
      - product by id
schemes:
- http
swagger: "2.0"
